# From https://github.com/wurstmeister/kafka-docker
version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9100:9100"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
